### ISSUE TITLE
Jump higher cheat crash

### ISSUE THREAD

**Issue by IniGisah** [ZeikJT/CrossCodeCheats#8]
My game crashed when i want to jump to higher platform with Jump Higher cheat is enabled. 

Here's the logs
```
map: [autumn.cubaum], version: [v1.4.2-3], platform: [Desktop], OS: [Linux], browser: [Chrome], browserVersion: [100], nwjsVersion: [0.63.1], 64bit: [true], webAudio: [true], sampleRate: [48000]

ReferenceError: e is not defined
    at b._checkForUpwardJump (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/mods/CrossCodeCheats-master/cheats.js:342:6)
    at b._checkForUpwardJump (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:31:266)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:586:434)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:32:345)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:4718:499)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:32:345)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:5031:392)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:32:345)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:6054:285)
    at b.update (chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/js/game.compiled.js:32:345)
```

**Comment by IniGisah** [comment]
I think it's fixed by adding an empty variable around this code

https://github.com/ZeikJT/CrossCodeCheats/blob/39beb00eb0bd7d9611aa60bbbe0d2218bc45ae31/cheats.js#L333-L346

I just tried with adding 
`let e;`
but i don't know how to do this properly

**Comment by ZeikJT** [comment]
Wow, don't know how that went undetected for so long! Guess no one was truly using it, thank you!

Should be fixed by https://github.com/ZeikJT/CrossCodeCheats/commit/94719aab4a3c9de6e706a5802cca3d9e30ddd6d5

**Comment by ShaunV2** [comment]
@ZeikJT It looks like you forgot to include the updated files in the latest release since this crash still happens.

I had to manually find what was changed and copy and paste it into the cheats.js file because version 1.4.2 doesn't come with this fix and the ccmod.json file is still showing the release as 1.4.1.

Note: After copying and applying the fix, the crash doesn't happen.

**Comment by krypciak** [comment]
As @ShaunV2 pointed out, this issue is not fixed in the `1.4.2` release archive.
